import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/page/Navbar";
import Footer from "@/page/Footer";

// นำเข้า Google Font JetBrains Mono และผูกเป็น CSS variable
const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "bd portfolio",
  icons: {
    icon: "/assets/icons/logobd.svg"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.className} font-mono antialiased`} // ใช้ font-mono แต่ค่าเป็น Source Code Pro
      >
        <nav >
          <Navbar/>
        </nav>
        <main className="min-h-screen lg:px-20 md:px-8 px-3">
          {children}
        </main>
        <footer className="relative z-50">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
